all:
	cd InfoServer; make
	cd MathServer; make
	cd InfoClient; make
	cd MathClient; make

clean:
	cd InfoServer; make clean
	cd MathServer; make clean
	cd InfoClient; make clean
	cd MathClient; make clean
